accessControl:
  salt: 63vcYfbl9lfRDs9v8GvUj81e6BgBgbwT
api:
  key: 70E99AD7893A498895A84D39F3C2B072
appearance:
  name: NetBox3D
controls:
- children:
  - command: M106 S%(speed)s
    input:
    - default: 255
      name: Speed (0-255)
      parameter: speed
    name: Enable Fan
    type: parametric_command
  - command: M107
    name: Disable Fan
    type: command
  name: Fan
  type: section
- children:
  - commands:
    - G91
    - G1 X10 F3000
    - G90
    name: Move X (static)
    type: commands
  - commands:
    - G91
    - G1 X%(distance)s F%(speed)s
    - G90
    input:
    - default: 10
      name: Distance
      parameter: distance
    - default: 3000
      name: Speed
      parameter: speed
    name: Move X (parametric)
    type: parametric_commands
  name: Example for multiple commands
  type: section
- children:
  - command: M114
    name: Get Position
    regex: X:([0-9.]+) Y:([0-9.]+) Z:([0-9.]+) E:([0-9.]+)
    template: 'Position: X={0}, Y={1}, Z={2}, E={3}'
    type: feedback_command
  name: Reporting
  type: section
devel:
  stylesheet: less
feature: {}
gcodeViewer: {}
plugins:
  discovery:
    httpPassword: null
    httpUsername: null
    model:
      description: null
      name: null
      number: null
      serial: null
      url: null
      vendor: null
      vendorUrl: null
    pathPrefix: null
    publicHost: null
    publicPort: null
    upnpUuid: c4cedab7-e638-400c-8296-d9b0e53242cb
    zeroConf: []
  helloworld:
    url: http://www.3dreprap.de
printerParameters: {}
printerProfiles:
  defaultProfile:
    axes:
      e:
        inverted: false
        speed: 300
      x:
        inverted: false
        speed: 6000
      y:
        inverted: false
        speed: 6000
      z:
        inverted: false
        speed: 200
    color: default
    extruder:
      count: 1
      nozzleDiameter: 0.4
      offsets:
      - - 0.0
        - 0.0
    heatedBed: true
    id: _default
    model: Generic RepRap Printer
    name: Default
    volume:
      depth: 200.0
      formFactor: rectangular
      height: 200.0
      origin: lowerleft
      width: 200.0
serial:
  baudrate: 115200
  port: /dev/ttyUSB1
  timeout: {}
server:
  firstRun: false
  secretKey: zZff04fvixChHDPEYvQYtcUClnpnBjPW
system:
  actions:
  - action: shutdown
    command: sudo shutdown -h now
    confirm: You are about to shutdown the system.
    name: Shutdown
  - action: reboot
    command: sudo shutdown -r now
    confirm: You are about to reboot the system.
    name: Reboot
  - action: streamon
    command: sudo service mjpg_streamer start
    confirm: false
    name: Start video stream
  - action: streamoff
    command: sudo service mjpg_streamer stop
    confirm: false
    name: Stop video stream
  - action: update
    command: rm -rf /tmp/config.log && cd /var/opt/NetBoxPrint && sudo /var/opt/NetBoxPrint/VH-Configs/Update-System.sh >> /tmp/config.log
      setup.py install
    confirm: You are about to update Octoprint.
    name: Update (git pull)
temperature: {}
webcam:
  ffmpeg: /usr/bin/avconv
  snapshot: http://192.168.0.42:8090/?action=snapshot
  stream: http://192.168.1.42:8090/?action=stream
  watermark: false
